### ISSUE TITLE
Replace all relevant pictures

### ISSUE THREAD

**Issue by z31t** [Ilaris-Tools/IlarisBrauerei#20]

**Comment by lukruh** [comment]
Das Landschaftsbild ist ziemlich sicher KI generiert und dann auf imgur hochgeladen ohne irgendwelche copyright angaben, ausserdem wirds von homebrewery genauso benutzt, ich glaub das können wir wohl erstmal drin lassen, sonst generier ich uns ein neues ;). 

Den Drachen würd ich ersetzen, der ist sehr DnD style finde ich.

**Comment by lukruh** [comment]
startseite ist gefixt.
das bild und credit beispiel hat noch bilder die durch ilaris assets ersetzt werden könnten.
Fürs cover hier ein paar ideen auf die schnelle: https://pixabay.com/collections/cover_examples-17097358/
