### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by z31t** [Ilaris-Tools/IlarisBrauerei#7]

**Comment by lukruh** [comment]
At least all buttons, snippets and css classes vor v0.1.

**Comment by lukruh** [comment]
css classes/snippets
- [x] toc, inhaltsverzeichnis
- [x] wide 
- [x] descriptive, textbox
- [x] note
- [x] bild beispiel (catwarrior)
- [x] Table Examples #42 

content
- [x] "brew not found" page
- [ ] ~permission denied page~
- [x] FAQ #22
